export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_FROM_KAKAO = 'FETCH_USERS_FROM_KAKAO';
export const LINK_FROM_KAKAOID_TO_CARTUSER = 'LINK_FROM_KAKAOID_TO_CARTUSER';
